export const USER_REGISTER = 'USER_REGISTER';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_VERIFY = 'USER_VERIFY';
export const USER_LOGOUT = 'USER_LOGOUT';

export const CHAT_MESSAGES_FETCH = 'CHAT_MESSAGES_FETCH';
export const CHAT_MESSAGE_SEND = 'CHAT_MESSAGE_SEND';
export const CHAT_FETCH_CHANNELS = 'CHAT_FETCH_CHANNELS';
export const CHAT_CREATE_CHANNEL = 'CHAT_CREATE_CHANNEL';
export const CHAT_DELETE_CHANNEL = 'CHAT_DELETE_CHANNEL';
export const CHAT_FETCH_MEMBERS = 'CHAT_FETCH_MEMBERS';

export const ERROR_EMIT = 'ERROR_EMIT';
export const ERROR_DISCARD = 'ERROR_DISCARD';
